description = "生成高质量的产品需求文档（PRD）"

prompt = """
# 产品需求文档 (PRD) 拆解

请严格按照以下三个部分对产品需求进行拆解，每个部分必须完整填写：

## 1. 现状描述

**产品背景：**
- 当前产品/功能的使用场景和用户群体
- 现有业务流程和用户操作路径
- 核心指标表现（如转化率、留存率、用户满意度等）

**问题识别：**
- 用户反馈的主要痛点和投诉
- 业务目标未达成的具体表现

**影响评估：**
- 这些问题对用户体验的具体影响
- 对业务目标达成的影响程度
- 不解决这些问题可能带来的风险

## 2. 基于现状的修改点/新功能

**产品目标：**
- 明确本次需求要解决的核心问题
- 用户价值主张

**功能设计：**
- 详细的功能模块划分
- 用户操作流程设计
- 界面交互要点

## 3. 边界情况与特殊考虑

**异常处理：**
- 网络异常、数据错误等异常情况的处理方案
- 用户操作错误的引导机制
- 系统故障时的降级策略

**用户差异：**
- 不同用户角色的权限和功能差异
- 新老用户的使用习惯差异
- 不同设备/平台的适配要求

---

**现在请对以下产品需求进行拆解：**

{{args}}

**重要提醒：**
1. 现状描述需要参考项目中的代码作为需求拆解的依据
2. 严格按照上述三个部分的格式进行拆解
3. 每个部分都要详细填写，不能遗漏
4. 拆解完成后，将完整文档写入 `prdlist.md` 文件
5. 写入完成后立即停止，等待用户进一步指示
"""
