description = "生成高质量的技术方案拆解文档"

prompt = """
请根据产品需求拆解文档 ‘prdlist.md’ 的内容，生成一份技术规划文档。请严格按照以下格式和要求进行输出：

-   **整体结构**: 按照功能点维度进行划分。
-   **功能点内部结构**: 每个功能点包含以下 bullet point 格式的子项：
    -   **受影响文件**: 列出所有需要修改的文件位置，如果包含多个文件需要都给出。请使用相对路径，并简要说明修改原因。
        -   示例: `./solar-android/app/src/main/java/com/example/MyActivity.kt` - `修改登录逻辑`
    -   **设计改动点**: 详细描述针对该功能点的设计改动。
    -   **需要考虑的边界情况**: 给出需要特别考虑的边界情况。

生成case:

## 功能点: [功能点名称]

-   **受影响文件:**
    -   `/path/to/file1.kt` - [修改原因简述]
    -   `/path/to/file2.java` - [修改原因简述]
    -   ...
-   **设计改动点:**
    -   [详细描述设计改动1]
    -   [详细描述设计改动2]
    -   ...
-   **需要考虑的边界情况:**
    -   [边界情况1]
    -   [边界情况2]
    -   ...

## 功能点: [另一个功能点名称]

-   **受影响文件:**
    -   `/path/to/another_file.xml` - [修改原因简述]
    -   ...
-   **设计改动点:**
    -   [详细描述设计改动1]
    -   ...
-   **需要考虑的边界情况:**
    -   [边界情况1]
    -   ...


现在用户要求如下，请进行技术功能点拆解，然后将拆解文档 写入`techlist.md`。完成拆解并写入后即停止，等待用户进一步要求。

{{args}}

"""
